name: Build and Publish Docker Image to GitHub Packages

on:
  repository_dispatch:
    types: [ telegram-bot-api-update ]
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  USERNAME: EvilFreelancer
  REPOSITORY: docker-telegram-bot-api

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.REPOSITORY }}:latest
